kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: bittrex-heikin-ashi-exporter
  name: bittrex-heikin-ashi-exporter
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: bittrex-heikin-ashi-exporter
  template:
    metadata:
      labels:
        k8s-app: bittrex-heikin-ashi-exporter
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: bittrex-heikin-ashi-exporter
        image: bcawthra/bittrex-heikin-ashi-exporter:latest
        args: ['--host', 'prometheus']
        ports:
        - containerPort: 9101
          protocol: TCP
